#!/bin/bash
##################################
#Created  :2018-05-05
#Version  :V1.0
#Author   :wenxiaobin
#Email    :wenxb01@mingyuanyun.com
##################################

function black()
{
    echo -e "\033[30m$1 \033[0m"
}
function red()
{
    echo -e "\033[31m$1 \033[0m"
}
function green()
{
    echo -e "\033[32m$1 \033[0m"
}
function blue()
{
    echo -e "\033[34m$1 \033[0m"
}
function white()
{
   echo -e "\033[37m$1 \033[0m"
}
function yellow()
{
    echo -e "\033[33m$1 \033[0m"   
}
