#!/bin/bash
##################################
#Created :2018-05-05
#Version :V1.0
#Author :wenxiaobin
#Email :wenxb01@mingyuanyun.com
##################################
source /usr/local/bin/error_prompt

if echo $1 | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null; then
    HOST_IP=$1
else
    HOST_NAME=$1
    HOST_IP=`grep ${HOST_NAME} /etc/hosts | cut -d' ' -f1`
fi

case $1 in
    manage_mirr)
        yellow "正在登陆镜像管理机器${HOST_IP} ${HOST_NAME}.../n"
        ssh -p 60001 root@${HOST_IP}
    ;;
    manage_prod)
        yellow "正在登陆生产堡垒机${HOST_IP} ${HOST_NAME}.../n"
        sshpass -f /etc/temp ssh -p 60022 wenxb@${HOST_IP}
    ;;
    mirr*)
        yellow "正在登陆镜像机器${HOST_IP} ${HOST_NAME}.../n"
        ssh wen${HOST_IP}
    ;;
    prod*)
        yellow "正在登陆生产机器${HOST_IP} ${HOST_NAME}.../n"
        ycgprod_login ${HOST_NAME} 
    ;;
    *)
        yellow "正在登陆测试环境${HOST_IP} .../n"
        ssh user1@${HOST_IP} || ssh root@${HOST_IP}   
    ;; 
esac 
