#!/bin/bash
##################################
#Created :2018-05-05
#Version :V1.0
#Author :wenxiaobin
#Email :wenxb01@mingyuanyun.com
##################################
cat /etc/hosts | sed -n '3,$p'
